### PR TITLE
librdkafka v2.3.0

### PR DESCRIPTION
**Pull request by emasab**

### CODE REVIEW

**Comment by mensfeld** [comment]
@emasab is this the "release" PR? That is, will there be a beta or something? I have "my" repros that I could use to thoughtfully test it prior to stable

**Comment by emasab** [comment]
No, this is for creating a release candidate, there will be more commits later

**Comment by emasab** [comment]
@mensfeld RC3 should be the last RC before the final release we plan before next Monday

**Comment by mensfeld** [comment]
@emasab thank you. I will do my best to run RC3 on my test suites "just in case" :)

**Pull request merged**
